import { app, BrowserWindow, ipcMain, nativeTheme } from "electron";
import * as fs from "fs";
import * as path from "path";
import { setWallpaper } from "wallpaper";
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require("electron-squirrel-startup")) {
  app.quit();
}

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 729,
    minHeight: 469,
    width: 715,
    minWidth: 715,
    maxWidth: 715,
    frame: false,
    titleBarStyle: "hiddenInset",
    vibrancy: "under-window",
    transparent: true,
    hasShadow: true,
    acceptFirstMouse: true,
    fullscreenable: false,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
    trafficLightPosition: { x: 20, y: 16 },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Enable DevTools in development mode
  if (process.env.NODE_ENV === "development") {
    mainWindow.webContents.on("before-input-event", (event, input) => {
      if (input.key === "F12") {
        mainWindow.webContents.toggleDevTools();
        event.preventDefault();
      }
    });
  }
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on("ready", createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    app.quit();
  }
});

app.on("activate", () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
app.whenReady().then(() => {
  ipcMain.handle("isDarkMode", () => nativeTheme.shouldUseDarkColors);
  nativeTheme.on("updated", () => {
    BrowserWindow.getAllWindows().forEach((win) => {
      win.webContents.send("theme-updated", nativeTheme.shouldUseDarkColors);
    });
  });

  ipcMain.handle("save-photos", async (_event, { files }) => {
    const userData = app.getPath("userData");
    const photosDir = path.join(userData, "kettle-panels", "photos");
    fs.mkdirSync(photosDir, { recursive: true });
    const metadataPath = path.join(photosDir, "metadata.json");
    let metadata: {
      [key: string]: { originalName: string; importedAt: string };
    } = {};
    if (fs.existsSync(metadataPath)) {
      try {
        metadata = JSON.parse(fs.readFileSync(metadataPath, "utf-8"));
      } catch (e) {
        metadata = {};
      }
    }
    for (const file of files) {
      const matches = file.dataUrl.match(/^data:(.+);base64,(.+)$/);
      if (!matches) continue;
      const buffer = Buffer.from(matches[2], "base64");
      const filePath = path.join(photosDir, file.guid);
      fs.writeFileSync(filePath, buffer);
      metadata[file.guid] = {
        originalName: file.name,
        importedAt: new Date().toISOString(),
      };
    }
    fs.writeFileSync(metadataPath, JSON.stringify(metadata, null, 2));
    scheduleAutoRotate();
    return { success: true };
  });

  ipcMain.handle("delete-photo", async (_event, { guid }) => {
    const userData = app.getPath("userData");
    const photosDir = path.join(userData, "kettle-panels", "photos");
    const metadataPath = path.join(photosDir, "metadata.json");
    let metadata: {
      [key: string]: { originalName: string; importedAt: string };
    } = {};
    if (fs.existsSync(metadataPath)) {
      try {
        metadata = JSON.parse(fs.readFileSync(metadataPath, "utf-8"));
      } catch (e) {
        metadata = {};
      }
    }
    const filePath = path.join(photosDir, guid);
    try {
      if (fs.existsSync(filePath)) fs.unlinkSync(filePath);
      if (metadata[guid]) {
        delete metadata[guid];
        fs.writeFileSync(metadataPath, JSON.stringify(metadata, null, 2));
      }
      scheduleAutoRotate();
      return { success: true };
    } catch (e) {
      return { success: false, error: e.message };
    }
  });

  ipcMain.handle("get-photos", async () => {
    const userData = app.getPath("userData");
    const photosDir = path.join(userData, "kettle-panels", "photos");
    const metadataPath = path.join(photosDir, "metadata.json");
    let metadata = {};
    if (fs.existsSync(metadataPath)) {
      try {
        metadata = JSON.parse(fs.readFileSync(metadataPath, "utf-8"));
      } catch (e) {
        metadata = {};
      }
    }
    const photos = Object.keys(metadata)
      .map((guid) => {
        const filePath = path.join(photosDir, guid);
        if (fs.existsSync(filePath)) {
          const buffer = fs.readFileSync(filePath);
          const base64 = buffer.toString("base64");
          return {
            url: `data:image/*;base64,${base64}`,
            guid,
          };
        }
        return null;
      })
      .filter(Boolean);
    return { photos };
  });

  ipcMain.handle("set-wallpaper", async (_event, { guid }) => {
    const userData = app.getPath("userData");
    const photosDir = path.join(userData, "kettle-panels", "photos");
    const filePath = path.join(photosDir, guid);
    try {
      await setWallpaper(filePath, { screen: "all" });
      return { success: true };
    } catch (e) {
      return { success: false, error: e.message };
    }
  });

  // Preferences handlers
  ipcMain.handle("get-preferences", async () => {
    const userData = app.getPath("userData");
    const prefsDir = path.join(userData, "kettle-panels");
    const prefsPath = path.join(prefsDir, "preferences.json");
    let prefs = { autoRotateInterval: 0 };
    if (fs.existsSync(prefsPath)) {
      try {
        prefs = JSON.parse(fs.readFileSync(prefsPath, "utf-8"));
      } catch (e) {
        prefs = { autoRotateInterval: 0 };
      }
    }
    return prefs;
  });

  ipcMain.handle("set-preferences", async (_event, prefs) => {
    const userData = app.getPath("userData");
    const prefsDir = path.join(userData, "kettle-panels");
    fs.mkdirSync(prefsDir, { recursive: true });
    const prefsPath = path.join(prefsDir, "preferences.json");
    fs.writeFileSync(prefsPath, JSON.stringify(prefs, null, 2));
    scheduleAutoRotate();
    return { success: true };
  });

  // --- Wallpaper Auto-Rotation Logic (Main Process) ---
  let autoRotateTimer: NodeJS.Timeout | null = null;
  let lastKnownInterval = 0;
  let lastKnownPhotos: string[] = [];
  let lastKnownGuid: string | null = null;

  function getPhotosList(): string[] {
    const userData = app.getPath("userData");
    const photosDir = path.join(userData, "kettle-panels", "photos");
    const metadataPath = path.join(photosDir, "metadata.json");
    let metadata = {};
    if (fs.existsSync(metadataPath)) {
      try {
        metadata = JSON.parse(fs.readFileSync(metadataPath, "utf-8"));
      } catch (e) {
        metadata = {};
      }
    }
    return Object.keys(metadata);
  }

  function getPreferences(): {
    autoRotateInterval: number;
    lastWallpaperChange?: number;
  } {
    const userData = app.getPath("userData");
    const prefsDir = path.join(userData, "kettle-panels");
    const prefsPath = path.join(prefsDir, "preferences.json");
    let prefs = { autoRotateInterval: 0 };
    if (fs.existsSync(prefsPath)) {
      try {
        prefs = JSON.parse(fs.readFileSync(prefsPath, "utf-8"));
      } catch (e) {
        prefs = { autoRotateInterval: 0 };
      }
    }
    return prefs;
  }

  function setPreferences(prefs: any) {
    const userData = app.getPath("userData");
    const prefsDir = path.join(userData, "kettle-panels");
    fs.mkdirSync(prefsDir, { recursive: true });
    const prefsPath = path.join(prefsDir, "preferences.json");
    fs.writeFileSync(prefsPath, JSON.stringify(prefs, null, 2));
  }

  async function rotateWallpaper() {
    const photos = getPhotosList();
    if (photos.length < 2) return;
    const prefs = getPreferences();
    const lastChange = prefs.lastWallpaperChange || 0;
    const now = Date.now();
    const interval = prefs.autoRotateInterval;
    if (interval <= 0) return;
    // Pick a new photo (not the current one)
    let available = photos.filter((g) => g !== lastKnownGuid);
    if (available.length === 0) available = photos;
    const nextGuid = available[Math.floor(Math.random() * available.length)];
    const userData = app.getPath("userData");
    const photosDir = path.join(userData, "kettle-panels", "photos");
    const filePath = path.join(photosDir, nextGuid);
    try {
      await setWallpaper(filePath, { screen: "all" });
      lastKnownGuid = nextGuid;
      setPreferences({ ...prefs, lastWallpaperChange: now });
    } catch (e) {
      // ignore
    }
  }

  function scheduleAutoRotate() {
    if (autoRotateTimer) clearTimeout(autoRotateTimer);
    const prefs = getPreferences();
    const interval = prefs.autoRotateInterval;
    if (interval <= 0) return;
    const photos = getPhotosList();
    if (photos.length < 2) return;
    const lastChange = prefs.lastWallpaperChange || 0;
    const now = Date.now();
    const timeSinceLast = now - lastChange;
    let delay = interval - timeSinceLast;
    if (delay <= 0) delay = 0;
    autoRotateTimer = setTimeout(async () => {
      await rotateWallpaper();
      scheduleAutoRotate();
    }, delay);
  }

  // Start auto-rotate on app ready
  scheduleAutoRotate();
});
