import { app, BrowserWindow, ipcMain, nativeTheme } from "electron";
import * as fs from "fs";
import * as path from "path";
import { setWallpaper } from "wallpaper";
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require("electron-squirrel-startup")) {
  app.quit();
}

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 729,
    minHeight: 469,
    width: 715,
    minWidth: 715,
    maxWidth: 715,
    frame: false,
    titleBarStyle: "hiddenInset",
    vibrancy: "under-window",
    transparent: true,
    hasShadow: true,
    acceptFirstMouse: true,
    fullscreenable: false,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
    trafficLightPosition: { x: 20, y: 16 },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Enable DevTools in development mode
  if (process.env.NODE_ENV === "development") {
    mainWindow.webContents.on("before-input-event", (event, input) => {
      if (input.key === "F12") {
        mainWindow.webContents.toggleDevTools();
        event.preventDefault();
      }
    });
  }
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on("ready", createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    app.quit();
  }
});

app.on("activate", () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
app.whenReady().then(() => {
  ipcMain.handle("isDarkMode", () => nativeTheme.shouldUseDarkColors);
  nativeTheme.on("updated", () => {
    BrowserWindow.getAllWindows().forEach((win) => {
      win.webContents.send("theme-updated", nativeTheme.shouldUseDarkColors);
    });
  });

  ipcMain.handle("save-photos", async (_event, { files }) => {
    const userData = app.getPath("userData");
    const photosDir = path.join(userData, "kettle-panels", "photos");
    fs.mkdirSync(photosDir, { recursive: true });
    const metadataPath = path.join(photosDir, "metadata.json");
    let metadata: {
      [key: string]: { originalName: string; importedAt: string };
    } = {};
    if (fs.existsSync(metadataPath)) {
      try {
        metadata = JSON.parse(fs.readFileSync(metadataPath, "utf-8"));
      } catch (e) {
        metadata = {};
      }
    }
    for (const file of files) {
      const matches = file.dataUrl.match(/^data:(.+);base64,(.+)$/);
      if (!matches) continue;
      const buffer = Buffer.from(matches[2], "base64");
      const filePath = path.join(photosDir, file.guid);
      fs.writeFileSync(filePath, buffer);
      metadata[file.guid] = {
        originalName: file.name,
        importedAt: new Date().toISOString(),
      };
    }
    fs.writeFileSync(metadataPath, JSON.stringify(metadata, null, 2));
    scheduleAutoRotate();
    return { success: true };
  });

  ipcMain.handle("delete-photo", async (_event, { guid }) => {
    const userData = app.getPath("userData");
    const photosDir = path.join(userData, "kettle-panels", "photos");
    const metadataPath = path.join(photosDir, "metadata.json");
    let metadata: {
      [key: string]: { originalName: string; importedAt: string };
    } = {};
    if (fs.existsSync(metadataPath)) {
      try {
        metadata = JSON.parse(fs.readFileSync(metadataPath, "utf-8"));
      } catch (e) {
        metadata = {};
      }
    }
    const filePath = path.join(photosDir, guid);
    try {
      if (fs.existsSync(filePath)) fs.unlinkSync(filePath);
      if (metadata[guid]) {
        delete metadata[guid];
        fs.writeFileSync(metadataPath, JSON.stringify(metadata, null, 2));
      }
      scheduleAutoRotate();
      return { success: true };
    } catch (e) {
      return { success: false, error: e.message };
    }
  });

  ipcMain.handle("get-photos", async () => {
    const userData = app.getPath("userData");
    const photosDir = path.join(userData, "kettle-panels", "photos");
    const metadataPath = path.join(photosDir, "metadata.json");
    let metadata = {};
    if (fs.existsSync(metadataPath)) {
      try {
        metadata = JSON.parse(fs.readFileSync(metadataPath, "utf-8"));
      } catch (e) {
        metadata = {};
      }
    }
    const photos = Object.keys(metadata)
      .map((guid) => {
        const filePath = path.join(photosDir, guid);
        if (fs.existsSync(filePath)) {
          const buffer = fs.readFileSync(filePath);
          const base64 = buffer.toString("base64");
          return {
            url: `data:image/*;base64,${base64}`,
            guid,
          };
        }
        return null;
      })
      .filter(Boolean);
    return { photos };
  });

  // --- Generated Image Management ---
  const GENERATED_DIR = "generated";
  const GENERATED_MAPPING = "mapping.json";
  const DEFAULT_STYLE = "default";

  // Use environment variable for API URL, fallback to sensible defaults
  const isDev = process.env.NODE_ENV === "development";
  const API_URL =
    process.env.API_URL ||
    (isDev ? "http://localhost:8000" : "https://your-production-api.com");

  function getGeneratedDir() {
    const userData = app.getPath("userData");
    const genDir = path.join(userData, "kettle-panels", GENERATED_DIR);
    fs.mkdirSync(genDir, { recursive: true });
    return genDir;
  }

  function getGeneratedMappingPath() {
    return path.join(getGeneratedDir(), GENERATED_MAPPING);
  }

  function readGeneratedMapping() {
    const mappingPath = getGeneratedMappingPath();
    if (fs.existsSync(mappingPath)) {
      try {
        return JSON.parse(fs.readFileSync(mappingPath, "utf-8"));
      } catch (e) {
        return {};
      }
    }
    return {};
  }

  function writeGeneratedMapping(mapping: any) {
    const mappingPath = getGeneratedMappingPath();
    fs.writeFileSync(mappingPath, JSON.stringify(mapping, null, 2));
  }

  async function fetchAndStoreGeneratedImage(
    guid: string,
    style: string = DEFAULT_STYLE
  ): Promise<string> {
    // Read the original image as base64
    const userData = app.getPath("userData");
    const photosDir = path.join(userData, "kettle-panels", "photos");
    const originalFilePath = path.join(photosDir, guid);
    if (!fs.existsSync(originalFilePath))
      throw new Error("Original image not found");
    const buffer = fs.readFileSync(originalFilePath);
    const base64 = buffer.toString("base64");
    // POST to FastAPI
    const apiUrl = `${API_URL}/image-gen`;
    const res = await fetch(apiUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ image: base64, style }),
    });
    if (!res.ok) throw new Error("Failed to fetch generated image from API");
    const json = await res.json();
    const generatedBase64 = json.image;
    if (!generatedBase64) throw new Error("No image returned from API");
    const genDir = getGeneratedDir();
    const genFileName = `${guid}_${style}`;
    const genFilePath = path.join(genDir, genFileName);
    fs.writeFileSync(genFilePath, Buffer.from(generatedBase64, "base64"));
    // Update mapping
    const mapping = readGeneratedMapping();
    if (!mapping[guid]) mapping[guid] = {};
    mapping[guid][style] = genFileName;
    writeGeneratedMapping(mapping);
    return genFilePath;
  }

  function getGeneratedImagePath(
    guid: string,
    style: string = DEFAULT_STYLE
  ): string | null {
    const mapping = readGeneratedMapping();
    if (mapping[guid] && mapping[guid][style]) {
      const genDir = getGeneratedDir();
      const genFilePath = path.join(genDir, mapping[guid][style]);
      if (fs.existsSync(genFilePath)) return genFilePath;
    }
    return null;
  }

  ipcMain.handle(
    "set-wallpaper",
    async (_event, { guid, style = DEFAULT_STYLE }) => {
      try {
        let genFilePath = getGeneratedImagePath(guid, style);
        if (!genFilePath) {
          genFilePath = await fetchAndStoreGeneratedImage(guid, style);
        }
        await setWallpaper(genFilePath, { screen: "all" });
        return { success: true };
      } catch (e) {
        return { success: false, error: e.message };
      }
    }
  );

  // Preferences handlers
  ipcMain.handle("get-preferences", async () => {
    const userData = app.getPath("userData");
    const prefsDir = path.join(userData, "kettle-panels");
    const prefsPath = path.join(prefsDir, "preferences.json");
    let prefs = { autoRotateInterval: 0 };
    if (fs.existsSync(prefsPath)) {
      try {
        prefs = JSON.parse(fs.readFileSync(prefsPath, "utf-8"));
      } catch (e) {
        prefs = { autoRotateInterval: 0 };
      }
    }
    return prefs;
  });

  ipcMain.handle("set-preferences", async (_event, prefs) => {
    const userData = app.getPath("userData");
    const prefsDir = path.join(userData, "kettle-panels");
    fs.mkdirSync(prefsDir, { recursive: true });
    const prefsPath = path.join(prefsDir, "preferences.json");
    fs.writeFileSync(prefsPath, JSON.stringify(prefs, null, 2));
    scheduleAutoRotate();
    return { success: true };
  });

  // --- Wallpaper Auto-Rotation Logic (Main Process) ---
  let autoRotateTimer: NodeJS.Timeout | null = null;
  let lastKnownGuid: string | null = null;

  function getPhotosList(): string[] {
    const userData = app.getPath("userData");
    const photosDir = path.join(userData, "kettle-panels", "photos");
    const metadataPath = path.join(photosDir, "metadata.json");
    let metadata = {};
    if (fs.existsSync(metadataPath)) {
      try {
        metadata = JSON.parse(fs.readFileSync(metadataPath, "utf-8"));
      } catch (e) {
        metadata = {};
      }
    }
    return Object.keys(metadata);
  }

  function getPreferences(): {
    autoRotateInterval: number;
    lastWallpaperChange?: number;
  } {
    const userData = app.getPath("userData");
    const prefsDir = path.join(userData, "kettle-panels");
    const prefsPath = path.join(prefsDir, "preferences.json");
    let prefs = { autoRotateInterval: 0 };
    if (fs.existsSync(prefsPath)) {
      try {
        prefs = JSON.parse(fs.readFileSync(prefsPath, "utf-8"));
      } catch (e) {
        prefs = { autoRotateInterval: 0 };
      }
    }
    return prefs;
  }

  function setPreferences(prefs: any) {
    const userData = app.getPath("userData");
    const prefsDir = path.join(userData, "kettle-panels");
    fs.mkdirSync(prefsDir, { recursive: true });
    const prefsPath = path.join(prefsDir, "preferences.json");
    fs.writeFileSync(prefsPath, JSON.stringify(prefs, null, 2));
  }

  async function rotateWallpaper() {
    const photos = getPhotosList();
    if (photos.length < 2) return;
    const prefs = getPreferences();
    const now = Date.now();
    const interval = prefs.autoRotateInterval;
    if (interval <= 0) return;
    // Pick a new photo (not the current one)
    let available = photos.filter((g) => g !== lastKnownGuid);
    if (available.length === 0) available = photos;
    const nextGuid = available[Math.floor(Math.random() * available.length)];
    try {
      // Use generated image (fetch/cached)
      let genFilePath = getGeneratedImagePath(nextGuid, DEFAULT_STYLE);
      if (!genFilePath) {
        genFilePath = await fetchAndStoreGeneratedImage(
          nextGuid,
          DEFAULT_STYLE
        );
      }
      await setWallpaper(genFilePath, { screen: "all" });
      lastKnownGuid = nextGuid;
      setPreferences({ ...prefs, lastWallpaperChange: now });
    } catch (e) {
      // ignore
    }
  }

  function scheduleAutoRotate() {
    if (autoRotateTimer) clearTimeout(autoRotateTimer);
    const prefs = getPreferences();
    const interval = prefs.autoRotateInterval;
    if (interval <= 0) return;
    const photos = getPhotosList();
    if (photos.length < 2) return;
    const lastChange = prefs.lastWallpaperChange || 0;
    const now = Date.now();
    const timeSinceLast = now - lastChange;
    let delay = interval - timeSinceLast;
    if (delay <= 0) delay = 0;
    autoRotateTimer = setTimeout(async () => {
      await rotateWallpaper();
      scheduleAutoRotate();
    }, delay);
  }

  // Start auto-rotate on app ready
  scheduleAutoRotate();
});
